### ISSUE TITLE
Emby crashing after update 14-5-2022

### ISSUE THREAD

**Issue by gcraenen** [linuxserver/docker-emby#49]
Was running fine before the update

From the logs:

`TargetSite: 

	

UnhandledException

System.AggregateException: System.AggregateException: One or more errors occurred. (Access to the path '/config/logs/embyserver-1.txt' is denied.)

 ---> System.UnauthorizedAccessException: Access to the path '/config/logs/embyserver-1.txt' is denied.

 ---> System.IO.IOException: Permission denied

   --- End of inner exception stack trace ---

   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)

   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)

   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)

   at Emby.Server.Implementations.Logging.FileLogger..ctor(String path)

   at Emby.Server.Implementations.Logging.SimpleLogManager.ReloadLogger(LogSeverity severity, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)

   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)

   at EmbyServer.Program.Main(String[] args)

Source: System.Private.CoreLib

TargetSite: Void ThrowAggregateException(System.Collections.Generic.List`1[System.Exception])

InnerException: System.UnauthorizedAccessException: Access to the path '/config/logs/embyserver-1.txt' is denied.

Source: System.Private.CoreLib

TargetSite: Void ThrowExceptionForIoErrno(ErrorInfo, System.String, Boolean, System.Func`2[Interop+ErrorInfo,Interop+ErrorInfo])

   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)

   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)

   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)

   at Emby.Server.Implementations.Logging.FileLogger..ctor(String path)

   at Emby.Server.Implementations.Logging.SimpleLogManager.ReloadLogger(LogSeverity severity, CancellationToken cancellationToken)

InnerException: System.IO.IOException: Permission denied

Source: 

`

**Comment by tiiime** [comment]
Same here, check `- /path/to/library:/config` dir's owner,  specify `PUID` and `PGID` in docker-compose.yml fixed.

**Comment by drizuid** [comment]
template not filled out
