### ISSUE TITLE
database disk image is malformed

### ISSUE THREAD

**Issue by KarlZeo** [linuxserver/docker-emby#50]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

emby server is running well.
## Current Behavior

emby server can't running.
## Steps to Reproduce

1. pull new docker images from 4.6.7 to 4.7.0
2. then, run the new docker image and throw an error.

## Environment
**OS:** Ubuntu Server 22.04
**CPU architecture:** x86_64
**How docker service was installed:**

I use official docker repo

## Command used to create docker container (run/create/compose/screenshot)

this is my docker compose file

```
emby:
    image: linuxserver/emby
    container_name: emby
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - https_proxy=http://172.17.0.1:7890
      - http_proxy=http://172.17.0.1:7890
      - all_proxy=socks5://172.17.0.1:7891
    volumes:
      - /root/dockerData/emby:/config
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri #optional
    restart: unless-stopped
```

## Docker logs

this is docker log

```
emby                        | Info Main: Application path: /app/emby/EmbyServer.dll
emby                        | Info Main: Emby
emby                        | 	Command line: /app/emby/EmbyServer.dll -programdata /config -ffdetect /app/emby/ffdetect -ffmpeg /app/emby/ffmpeg -ffprobe /app/emby/ffprobe -restartexitcode 3
emby                        | 	Operating system: Linux version 5.15.0-30-generic (buildd@lgw01-amd64-058) (gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #31-Ubuntu SMP
emby                        | 	Framework: .NET 6.0.2
emby                        | 	OS/Process: x64/x64
emby                        | 	Runtime: app/emby/System.Private.CoreLib.dll
emby                        | 	Processor count: 16
emby                        | 	Data path: /config
emby                        | 	Application path: /app/emby
emby                        | Info Main: Logs path: /config/logs
emby                        | Info Main: Cache path: /config/cache
emby                        | Info Main: Internal metadata path: /config/metadata
emby                        | Info Main: Transcoding temporary files path: /config/transcoding-temp
emby                        | Info App: Application version: 4.7.0.60
emby                        | Info App: Loading assemblies
emby                        | Info App: File /config/plugins/DvdMounter.dll has version 1.0.0.0
emby                        | Info App: File /app/emby/plugins/DvdMounter.dll has version 1.0.0.0
emby                        | Info App: File /config/plugins/Emby.M3UTuner.dll has version 1.0.13.0
emby                        | Info App: File /app/emby/plugins/Emby.M3UTuner.dll has version 1.0.13.0
emby                        | Info App: File /config/plugins/MovieDb.dll has version 1.5.6.0
emby                        | Info App: File /app/emby/plugins/MovieDb.dll has version 1.5.6.0
emby                        | Info App: File /config/plugins/Emby.Webhooks.dll has version 1.0.19.0
emby                        | Info App: File /app/emby/plugins/Emby.Webhooks.dll has version 1.0.19.0
emby                        | Info App: File /config/plugins/EmbyGuideData.dll has version 1.0.7.0
emby                        | Info App: File /app/emby/plugins/EmbyGuideData.dll has version 1.0.7.0
emby                        | Info App: File /config/plugins/NfoMetadata.dll has version 1.0.67.0
emby                        | Info App: File /app/emby/plugins/NfoMetadata.dll has version 1.0.67.0
emby                        | Info App: File /config/plugins/Emby.Server.CinemaMode.dll has version 1.0.40.0
emby                        | Info App: File /app/emby/plugins/Emby.Server.CinemaMode.dll has version 1.0.40.0
emby                        | Info App: File /config/plugins/Tvdb.dll has version 1.2.6.0
emby                        | Info App: File /app/emby/plugins/Tvdb.dll has version 1.2.6.0
emby                        | Info App: File /config/plugins/Fanart.dll has version 1.0.13.0
emby                        | Info App: File /app/emby/plugins/Fanart.dll has version 1.0.13.0
emby                        | Info App: File /config/plugins/Emby.PortMapper.dll has version 1.1.1.0
emby                        | Info App: File /app/emby/plugins/Emby.PortMapper.dll has version 1.1.1.0
emby                        | Info App: File /config/plugins/MusicBrainz.dll has version 1.0.18.0
emby                        | Info App: File /app/emby/plugins/MusicBrainz.dll has version 1.0.18.0
emby                        | Info App: File /config/plugins/StudioImages.dll has version 1.0.3.0
emby                        | Info App: File /app/emby/plugins/StudioImages.dll has version 1.0.3.0
emby                        | Info App: File /config/plugins/Emby.XmlTV.dll has version 1.0.5.0
emby                        | Info App: File /app/emby/plugins/Emby.XmlTV.dll has version 1.0.5.0
emby                        | Info App: File /config/plugins/BlurayMounter.dll has version 1.0.0.0
emby                        | Info App: File /app/emby/plugins/BlurayMounter.dll has version 1.0.0.0
emby                        | Info App: File /config/plugins/OMDb.dll has version 1.0.17.0
emby                        | Info App: File /app/emby/plugins/OMDb.dll has version 1.0.17.0
emby                        | Info App: File /config/plugins/OpenSubtitles.dll has version 1.0.31.0
emby                        | Info App: File /app/emby/plugins/OpenSubtitles.dll has version 1.0.31.0
emby                        | Info App: File /config/plugins/Emby.Dlna.dll has version 1.0.78.0
emby                        | Info App: File /app/emby/plugins/Emby.Dlna.dll has version 1.0.78.0
emby                        | Info App: File /config/plugins/SchedulesDirect.dll has version 1.0.2.0
emby                        | Info App: File /app/emby/plugins/SchedulesDirect.dll has version 1.0.2.0
emby                        | Info App: File /config/plugins/AudioDb.dll has version 1.0.15.0
emby                        | Info App: File /app/emby/plugins/AudioDb.dll has version 1.0.15.0
emby                        | Info App: Loading DvdMounter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/DvdMounter.dll
emby                        | Info App: Loading EmbyScripterX, Version=3.0.5.5, Culture=neutral, PublicKeyToken=null from /config/plugins/EmbyScripterX.dll
emby                        | Info App: Loading Emby.M3UTuner, Version=1.0.13.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Emby.M3UTuner.dll
emby                        | Info App: Loading AutoBoxSets, Version=1.2.6.0, Culture=neutral, PublicKeyToken=null from /config/plugins/AutoBoxSets.dll
emby                        | Info App: Loading XmlMetadata, Version=3.4.6.0, Culture=neutral, PublicKeyToken=null from /config/plugins/XmlMetadata.dll
emby                        | Info App: Loading Trakt, Version=3.5.6.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Trakt.dll
emby                        | Info App: Loading MovieDb, Version=1.5.6.0, Culture=neutral, PublicKeyToken=null from /config/plugins/MovieDb.dll
emby                        | Info App: Loading Emby.Webhooks, Version=1.0.19.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Emby.Webhooks.dll
emby                        | Info App: Loading EmbyGuideData, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null from /config/plugins/EmbyGuideData.dll
emby                        | Info App: Loading Lastfm, Version=1.0.25.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Lastfm.dll
emby                        | Info App: Loading Emby.Plugin.TelegramNotification, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Emby.Plugin.TelegramNotification.dll
emby                        | Info App: Loading NfoMetadata, Version=1.0.67.0, Culture=neutral, PublicKeyToken=null from /config/plugins/NfoMetadata.dll
emby                        | Info App: Loading Douban, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Douban.dll
emby                        | Info App: Loading InfuseSync, Version=1.4.1.0, Culture=neutral, PublicKeyToken=null from /config/plugins/InfuseSync.dll
emby                        | Info App: Loading Emby.Server.CinemaMode, Version=1.0.40.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Emby.Server.CinemaMode.dll
emby                        | Info App: Loading Tvdb, Version=1.2.6.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Tvdb.dll
emby                        | Info App: Loading JavScraper, Version=1.2021.622.2145, Culture=neutral, PublicKeyToken=null from /config/plugins/JavScraper.dll
emby                        | Info App: Loading Fanart, Version=1.0.13.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Fanart.dll
emby                        | Info App: Loading Emby.PortMapper, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Emby.PortMapper.dll
emby                        | Info App: Loading MusicBrainz, Version=1.0.18.0, Culture=neutral, PublicKeyToken=null from /config/plugins/MusicBrainz.dll
emby                        | Info App: Loading StudioImages, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null from /config/plugins/StudioImages.dll
emby                        | Info App: Loading Emby.XmlTV, Version=1.0.5.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Emby.XmlTV.dll
emby                        | Info App: Loading BlurayMounter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/BlurayMounter.dll
emby                        | Info App: Loading OMDb, Version=1.0.17.0, Culture=neutral, PublicKeyToken=null from /config/plugins/OMDb.dll
emby                        | Info App: Loading MediaBrowser.Plugins.Anime, Version=1.4.8.0, Culture=neutral, PublicKeyToken=null from /config/plugins/MediaBrowser.Plugins.Anime.dll
emby                        | Info App: Loading OpenSubtitles, Version=1.0.31.0, Culture=neutral, PublicKeyToken=null from /config/plugins/OpenSubtitles.dll
emby                        | Info App: Loading CoverArt, Version=4.1.17.0, Culture=neutral, PublicKeyToken=null from /config/plugins/CoverArt.dll
emby                        | Info App: Loading Emby.Dlna, Version=1.0.78.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Emby.Dlna.dll
emby                        | Info App: Loading IMVDb, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/IMVDb.dll
emby                        | Info App: Loading SchedulesDirect, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null from /config/plugins/SchedulesDirect.dll
emby                        | Info App: Loading AudioDb, Version=1.0.15.0, Culture=neutral, PublicKeyToken=null from /config/plugins/AudioDb.dll
emby                        | Info App: Loading Emby.Api, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info App: Loading Emby.Web, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info App: Loading MediaBrowser.Model, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info App: Loading MediaBrowser.Common, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info App: Loading MediaBrowser.Controller, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info App: Loading Emby.Providers, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info App: Loading Emby.Photos, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info App: Loading Emby.Server.Implementations, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info App: Loading Emby.LiveTV, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info App: Loading Emby.ActivityLog, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info App: Loading Emby.Server.MediaEncoding, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info App: Loading Emby.LocalMetadata, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info App: Loading Emby.Notifications, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info App: Loading Emby.Codecs.Dxva, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info App: Loading Emby.Codecs, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info App: Loading Emby.Server.Connect, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info App: Loading Emby.Server.Sync, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info App: Loading EmbyServer, Version=4.7.0.60, Culture=neutral, PublicKeyToken=null
emby                        | Info SqliteUserRepository: Sqlite version: 3.35.5
emby                        | Info SqliteUserRepository: Sqlite compiler options: COMPILER=gcc-8.3.0,ENABLE_COLUMN_METADATA,ENABLE_DBSTAT_VTAB,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS3_TOKENIZER,ENABLE_FTS4,ENABLE_FTS5,ENABLE_GEOPOLY,ENABLE_JSON1,ENABLE_MATH_FUNCTIONS,ENABLE_PREUPDATE_HOOK,ENABLE_RTREE,ENABLE_SESSION,ENABLE_UNLOCK_NOTIFY,ENABLE_UPDATE_DELETE_LIMIT,LIKE_DOESNT_MATCH_BLOBS,MAX_SCHEMA_RETRY=25,MAX_VARIABLE_NUMBER=250000,OMIT_LOOKASIDE,SECURE_DELETE,THREADSAFE=1
emby                        | Info SqliteUserRepository: Opening sqlite connection to /config/data/users.db
emby                        | Info SqliteUserRepository: Default journal_mode for /config/data/users.db is wal
emby                        | Info ActivityRepository: Opening sqlite connection to /config/data/activitylog.db
emby                        | Info ActivityRepository: Default journal_mode for /config/data/activitylog.db is wal
emby                        | Info SqliteDisplayPreferencesRepository: Opening sqlite connection to /config/data/displaypreferences.db
emby                        | Info SqliteDisplayPreferencesRepository: Default journal_mode for /config/data/displaypreferences.db is wal
emby                        | Info App: Adding HttpListener prefix http://+:8096/
emby                        | Info NetworkManager: Detecting local network addresses
emby                        | Info NetworkManager: networkInterface: Ethernet eth0, Speed: 10000000000, Description: eth0
emby                        | Info NetworkManager: GatewayAddresses: 172.17.0.1
emby                        | Info NetworkManager: UnicastAddresses: 172.17.0.2
emby                        | Info NetworkManager: networkInterface: Loopback lo, Speed: -1, Description: lo
emby                        | Info NetworkManager: GatewayAddresses:
emby                        | Info NetworkManager: UnicastAddresses: 127.0.0.1
emby                        | Info NetworkManager: Detected local ip addresses: 172.17.0.2, 127.0.0.1
emby                        | Info AuthenticationRepository: Opening sqlite connection to /config/data/authentication.db
emby                        | Info AuthenticationRepository: Default journal_mode for /config/data/authentication.db is wal
emby                        | Info SqliteItemRepository: Opening sqlite connection to /config/data/library.db
emby                        | Info SqliteItemRepository: Default journal_mode for /config/data/library.db is wal
emby                        | Info SqliteItemRepository: cache_size is -98304
emby                        | Info SqliteItemRepository: page_size is 4096
emby                        | Error Main: Error in appHost.Init
emby                        | 	*** Error Report ***
emby                        | 	Version: 4.7.0.60
emby                        | 	Command line: /app/emby/EmbyServer.dll -programdata /config -ffdetect /app/emby/ffdetect -ffmpeg /app/emby/ffmpeg -ffprobe /app/emby/ffprobe -restartexitcode 3
emby                        | 	Operating system: Linux version 5.15.0-30-generic (buildd@lgw01-amd64-058) (gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #31-Ubuntu SMP
emby                        | 	Framework: .NET 6.0.2
emby                        | 	OS/Process: x64/x64
emby                        | 	Runtime: app/emby/System.Private.CoreLib.dll
emby                        | 	Processor count: 16
emby                        | 	Data path: /config
emby                        | 	Application path: /app/emby
emby                        | 	SQLitePCL.pretty.SQLiteException: Corrupt: database disk image is malformed
emby                        | 	SQLitePCL.pretty.SQLiteException: Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown.
emby                        | 	   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
emby                        | 	   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
emby                        | 	   at SQLitePCL.pretty.StatementImpl.MoveNext()
emby                        | 	   at SQLitePCL.pretty.DatabaseConnection.ExecuteAll(IDatabaseConnection This, String sql)
emby                        | 	   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize(SqliteUserDataRepository userDataRepo, IUserManager userManager)
emby                        | 	   at Emby.Server.Implementations.ApplicationHost.InitDatabases()
emby                        | 	   at Emby.Server.Implementations.ApplicationHost.Init()
emby                        | 	   at EmbyServer.HostedService.StartAsync(CancellationToken cancellationToken)
emby                        | 	Source: SQLitePCL.pretty
emby                        | 	TargetSite: Void CheckOk(SQLitePCLEx.sqlite3, Int32)
emby                        |
emby                        | Info Main: Shutdown complete
^CERROR: Aborting.
```

well.This problem is only show on version 4.7.0.

when I downgrade to 4.6.7. The emby server is running well.

**Comment by drizuid** [comment]
As we support the container and not the application, we don't really have a way to determine what the upstream devs did to cause the issue. It's best to seek help from them.
