### ISSUE TITLE
[BUG] Error in CreateSsdpUdpSocket

### ISSUE THREAD

**Issue by MrLinford** [linuxserver/docker-emby#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On launch log show:
`Warn App: SetSocketOption 'MulticastLocalAdminAddress' failed for IP address '192.168.1.225': Unknown socket error
Error App: Error in CreateSsdpUdpSocket. IPAddress: 192.168.1.225
        *** Error Report ***
        Version: 4.7.13.0
        Command line: /app/emby/EmbyServer.dll -programdata /config -ffdetect /app/emby/ffdetect -ffmpeg /app/emby/ffmpeg -ffprobe /app/emby/ffprobe -restartexitcode 3
        Operating system: Linux version 5.19.17-Unraid (root@Develop) (gcc (GCC) 12.2.0, GNU ld version 2.39-slack151) #2 SMP PREEMPT_DYNAMIC Wed Nov 2 11:54:15 PDT 2022
        Framework: .NET 6.0.14
        OS/Process: x64/x64
        Runtime: app/emby/System.Private.CoreLib.dll
        Processor count: 8
        Data path: /config
        Application path: /app/emby
        System.Net.Sockets.SocketException: System.Net.Sockets.SocketException (0xFFFDFFFE): Unknown socket error
           at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
           at System.Net.Sockets.Socket.SetMulticastOption(SocketOptionName optionName, MulticastOption MR)
           at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Object optionValue)
           at Rssdp.SsdpCommunicationsServer.CreateSsdpUdpSocket(IPAddress localIpAddress, Int32 localPort, List`1 localAddresses)
           at Rssdp.SsdpCommunicationsServer.BeginListeningForBroadcasts(CancellationToken cancellationToken)
        Source: System.Net.Sockets
        TargetSite: Void UpdateStatusAfterSocketErrorAndThrowException(System.Net.Sockets.SocketError, System.String)`

Only since updating to [4.7.13.0-ls157](https://github.com/linuxserver/docker-emby/releases/tag/4.7.13.0-ls157)

### Steps To Reproduce

.

### Environment

```markdown
- OS:unraid
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='emby'
  --net='bridge'
  -e TZ="Europe/London"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Vault"
  -e HOST_CONTAINERNAME="emby"
  -e 'DOCKER_MODS'='ghcr.io/gilbn/theme.park:emby'
  -e 'TP_THEME'='nord'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8096]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/emby-logo.png'
  -p '8096:8096/tcp'
  -p '8920:8920/tcp'
  -v '/mnt/user/nas/Videos/':'/data/media':'rw'
  -v '/mnt/user/appdata/emby':'/config':'rw'
  --device='/dev/dri' 'lscr.io/linuxserver/emby'
087aeab3d204054e72bbbb126cdb1765e2813a18b4073793b7ed25e4ff1842c1
```

### Container logs

```bash
.
```

**Comment by MrLinford** [comment]
Updated OP with Docker Creation

**Comment by MrLinford** [comment]
Appears not to be linked to 4.7.13. Rolled back to 4.7.12 and the same issue is present.
